### ISSUE TITLE
MemoryError when trying to merge large lists. 

### ISSUE THREAD

**Issue by VoidOner** [k4m4/dymerge#6]
[+] Merging DictionariesTraceback (most recent call last):
  File "dymerge.py", line 459, in <module>
    main()
  File "dymerge.py", line 427, in main
    readFiles()
  File "dymerge.py", line 109, in readFiles
    lines = myFile.readlines()
MemoryError

**Comment by k4m4** [comment]
Hi there @VoidOner. DyMerge has been developed for merging small, target-based dictionaries and cannot handle massive files. Please have a look at my post [*Why DyMerge Sucks*](https://nikolaskama.me/why-dymerge-sucks/) and let me know if you have any further questions (you can reopen this issue). Thanks!
